name: aggregate share count

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  run-dataflow:
    runs-on: ubuntu-latest
    name: aggregate blog data
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.1.4
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Authenticate on GCS
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./aggregator/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-v1-

      - run: |
          cd aggregator
          pip3 install -r requirements.txt
          python3 aggregator.py --project ${{ secrets.GCP_PROJECT_ID }} \
            --setup_file ./setup.py \
            --runner DirectRunner \
            --region asia-northeast1 \
            --temp_location gs://${{ secrets.GCP_DATAFLOW_STORAGE }}/temp \
            --job_name aggregate \
            --dataset ${{ secrets.GCP_PROJECT_ID }}:blog_data \
            --env prod \
            --domain swfz.hatenablog.com \
            --input 'gs://${{ secrets.GCP_INPUT_STORAGE }}/share-count/service=*/*' \
            --output gs://${{ secrets.GCP_DATAFLOW_STORAGE }}/results/output

  slack-notify:
    if: always()
    needs: [run-dataflow]
    name: post slack
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@v1.0.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
