name: aggregator test

on: [push]

jobs:
  typecheck-aggregator:
    runs-on: ubuntu-latest
    name: typecheck(aggregator.py)
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - uses: actions/cache@v3.0.11
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./aggregator/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - run: |
          cd aggregator
          pip3 install -r requirements.txt
          mypy aggregator.py

  typecheck-timeseries:
    runs-on: ubuntu-latest
    name: typecheck(timeseries.py)
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - uses: actions/cache@v3.0.11
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./aggregator/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - run: |
          cd aggregator
          pip3 install -r requirements.txt
          mypy timeseries.py


  aggregator:
    runs-on: ubuntu-latest
    name: input output test(aggregator.py)
    needs: typecheck-aggregator
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - uses: actions/cache@v3.0.11
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./aggregator/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - run: |
          cd aggregator
          pip3 install -r requirements.txt
          green aggregator_test.py

  timeseries:
    runs-on: ubuntu-latest
    name: input output test(timeseries.py)
    needs: typecheck-timeseries
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - uses: actions/cache@v3.0.11
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./aggregator/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - run: |
          cd aggregator
          pip3 install -r requirements.txt
          green timeseries_test.py

  slack-notify:
    if: always()
    needs: [typecheck-aggregator, typecheck-timeseries, aggregator, timeseries]
    name: post slack
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@v1.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
