name: deploy cloud schduler

on:
  push:
    paths:
      - '.github/workflows/deploy-scheduler.yml'

jobs:
  deploy-publish-collector-analytics-job:
    runs-on: ubuntu-latest
    name: deploy publish-collector-analytics-job
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate on GCS
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true
      - run: |
          gcloud scheduler jobs update pubsub publish-collector-analytics-job --schedule="0 10 * * *" --topic=memo-collector-analytics --message-body='{"url": "https://swfz.hatenablog.com", "service": "analytics"}' --time-zone="Asia/Tokyo"

  # deploy-publish-job:
  #   runs-on: ubuntu-latest
  #   name: deploy publish-job
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Authenticate on GCS
  #       uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  #       with:
  #         project_id: ${{ secrets.GCP_PROJECT_ID }}
  #         service_account_email: ${{ secrets.GCP_EMAIL }}
  #         service_account_key: ${{ secrets.GCP_KEY }}
  #         export_default_credentials: true
  #     - run: |
  #       gcloud scheduler jobs update pubsub publish-job --schedule="2 * * * *" --topic=memo-collector-publish --message-body="{}" --time-zone="Asia/Tokyo"
  #
  # deploy-publish-timeseries-hatenastatus-job:
  #   runs-on: ubuntu-latest
  #   name: deploy publish-timeseries-hatenastatus-job
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Authenticate on GCS
  #       uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  #       with:
  #         project_id: ${{ secrets.GCP_PROJECT_ID }}
  #         service_account_email: ${{ secrets.GCP_EMAIL }}
  #         service_account_key: ${{ secrets.GCP_KEY }}
  #         export_default_credentials: true
  #     - run: |
  #       gcloud scheduler jobs update pubsub publish-timeseries-hatenastatus-job --schedule="2 10 * * *" --topic=memo-timeseries-hatenastatus --message-body='{"url": "https://swfz.hatenablog.com", "service": "hatenastatus"}' --time-zone="Asia/Tokyo"
