name: deploy cloud schduler

on:
  push:
    paths:
      - '.github/workflows/deploy-scheduler.yml'

jobs:
  deploy-publish-collector-analytics-job:
    runs-on: ubuntu-latest
    name: deploy publish-collector-analytics-job
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Authenticate on GCS
        uses: google-github-actions/setup-gcloud@v0.6.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true
      - run: |
          gcloud scheduler jobs update pubsub publish-collector-analytics-job --schedule="0 10 * * *" --topic=memo-collector-analytics --message-body='{"url": "https://swfz.hatenablog.com", "service": "analytics", "viewId": "${{ secrets.ANALYTICS_VIEW_ID }}"}' --time-zone="Asia/Tokyo"

  deploy-publish-job:
    runs-on: ubuntu-latest
    name: deploy publish-job
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Authenticate on GCS
        uses: google-github-actions/setup-gcloud@v0.6.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true
      - run: |
          gcloud scheduler jobs update pubsub publish-job --schedule="2 * * * *" --topic=memo-collector-publish --message-body="{}" --time-zone="Asia/Tokyo"

  deploy-publish-timeseries-hatenastatus-job:
    runs-on: ubuntu-latest
    name: deploy publish-timeseries-hatenastatus-job
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Authenticate on GCS
        uses: google-github-actions/setup-gcloud@v0.6.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true
      - run: |
          gcloud scheduler jobs update pubsub publish-timeseries-hatenastatus-job --schedule="2 10 * * *" --topic=memo-timeseries-hatenastatus --message-body='{"url": "https://swfz.hatenablog.com", "service": "hatenastatus"}' --time-zone="Asia/Tokyo"

  slack-notify:
    if: always()
    needs: [deploy-publish-collector-analytics-job, deploy-publish-job, deploy-publish-timeseries-hatenastatus-job]
    name: post slack
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@v1.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
