name: timeseries metric
on:
  push:
  schedule:
    - cron: '0 2 * * *'

jobs:
  :
    runs-on: ubuntu-latest
    name: check storage by article url
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate on GCS
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true
      - name: check timestamp
        run: |
          gsutil ls -l 'gs://memo-raw-data/share-count/service=*/*' | ./gs-lt.sh



