name: check gcs timestamp
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 15 * * *'

jobs:
  monitor-gcs:
    runs-on: ubuntu-latest
    name: check storage updated
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Authenticate on GCS
        uses: google-github-actions/setup-gcloud@v0.6.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true
      - name: check timestamp
        run: |
          gsutil ls -l 'gs://memo-raw-data/share-count/service=*/*' | sed -e '$d' | ./gs-lt.sh

  slack-notify:
    if: always()
    needs: [monitor-gcs]
    name: post slack
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@v1.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
